### ISSUE TITLE
 IndexError: list index out of range main = tree.xpath('//tbody')[0]

### ISSUE THREAD

**Issue by YubinXie** [PureDarwin/googlesites2markdown#1]
Thanks for making this repo.

I got the following error when I tried to convert my google sites:

```
Traceback (most recent call last):
  File "googlesites2markdown", line 34, in <module>
    main = tree.xpath('//tbody')[0]
IndexError: list index out of range
```

**Comment by probonopd** [comment]
Thank you very much. Maybe you can figure it out. I have not used this code in years and do no longer maintain it. Thanks for your understanding.

**Comment by leili-plantmicrobe** [comment]
> Thanks for making this repo.
> 
> I got the following error when I tried to convert my google sites:
> 
> ```
> Traceback (most recent call last):
>   File "googlesites2markdown", line 34, in <module>
>     main = tree.xpath('//tbody')[0]
> IndexError: list index out of range
> ```

Do you figure it out, I also have the same problems. Thanks!
